# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rio_control_node/Current_Limit_Configuration.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Current_Limit_Configuration(genpy.Message):
  _md5sum = "0b094982e5c4f2662f97e3e7f3a069b0"
  _type = "rio_control_node/Current_Limit_Configuration"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool enable
float64 current_limit
float64 trigger_threshold_current
float64 trigger_threshold_time"""
  __slots__ = ['enable','current_limit','trigger_threshold_current','trigger_threshold_time']
  _slot_types = ['bool','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       enable,current_limit,trigger_threshold_current,trigger_threshold_time

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Current_Limit_Configuration, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.enable is None:
        self.enable = False
      if self.current_limit is None:
        self.current_limit = 0.
      if self.trigger_threshold_current is None:
        self.trigger_threshold_current = 0.
      if self.trigger_threshold_time is None:
        self.trigger_threshold_time = 0.
    else:
      self.enable = False
      self.current_limit = 0.
      self.trigger_threshold_current = 0.
      self.trigger_threshold_time = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B3d().pack(_x.enable, _x.current_limit, _x.trigger_threshold_current, _x.trigger_threshold_time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 25
      (_x.enable, _x.current_limit, _x.trigger_threshold_current, _x.trigger_threshold_time,) = _get_struct_B3d().unpack(str[start:end])
      self.enable = bool(self.enable)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B3d().pack(_x.enable, _x.current_limit, _x.trigger_threshold_current, _x.trigger_threshold_time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 25
      (_x.enable, _x.current_limit, _x.trigger_threshold_current, _x.trigger_threshold_time,) = _get_struct_B3d().unpack(str[start:end])
      self.enable = bool(self.enable)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B3d = None
def _get_struct_B3d():
    global _struct_B3d
    if _struct_B3d is None:
        _struct_B3d = struct.Struct("<B3d")
    return _struct_B3d
