# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rio_control_node/Encoder_Data.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import rio_control_node.msg

class Encoder_Data(genpy.Message):
  _md5sum = "6f99afe2c4edd57a081cd7d3afe865aa"
  _type = "rio_control_node/Encoder_Data"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """Encoder_Sensor_Data[] encoderData
================================================================================
MSG: rio_control_node/Encoder_Sensor_Data
int32 id
float64 position
float64 velocity
bool faulted"""
  __slots__ = ['encoderData']
  _slot_types = ['rio_control_node/Encoder_Sensor_Data[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       encoderData

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Encoder_Data, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.encoderData is None:
        self.encoderData = []
    else:
      self.encoderData = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.encoderData)
      buff.write(_struct_I.pack(length))
      for val1 in self.encoderData:
        _x = val1
        buff.write(_get_struct_i2dB().pack(_x.id, _x.position, _x.velocity, _x.faulted))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.encoderData is None:
        self.encoderData = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.encoderData = []
      for i in range(0, length):
        val1 = rio_control_node.msg.Encoder_Sensor_Data()
        _x = val1
        start = end
        end += 21
        (_x.id, _x.position, _x.velocity, _x.faulted,) = _get_struct_i2dB().unpack(str[start:end])
        val1.faulted = bool(val1.faulted)
        self.encoderData.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.encoderData)
      buff.write(_struct_I.pack(length))
      for val1 in self.encoderData:
        _x = val1
        buff.write(_get_struct_i2dB().pack(_x.id, _x.position, _x.velocity, _x.faulted))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.encoderData is None:
        self.encoderData = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.encoderData = []
      for i in range(0, length):
        val1 = rio_control_node.msg.Encoder_Sensor_Data()
        _x = val1
        start = end
        end += 21
        (_x.id, _x.position, _x.velocity, _x.faulted,) = _get_struct_i2dB().unpack(str[start:end])
        val1.faulted = bool(val1.faulted)
        self.encoderData.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i2dB = None
def _get_struct_i2dB():
    global _struct_i2dB
    if _struct_i2dB is None:
        _struct_i2dB = struct.Struct("<i2dB")
    return _struct_i2dB
