# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rio_control_node/IMU_Data.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import rio_control_node.msg

class IMU_Data(genpy.Message):
  _md5sum = "db308b5f7c3a2dfbebaf919da37ee68f"
  _type = "rio_control_node/IMU_Data"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """IMU_Sensor_Data[] imuData
================================================================================
MSG: rio_control_node/IMU_Sensor_Data
float64 yaw
float64 pitch
float64 roll
float64 yawrate
"""
  __slots__ = ['imuData']
  _slot_types = ['rio_control_node/IMU_Sensor_Data[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       imuData

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(IMU_Data, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.imuData is None:
        self.imuData = []
    else:
      self.imuData = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.imuData)
      buff.write(_struct_I.pack(length))
      for val1 in self.imuData:
        _x = val1
        buff.write(_get_struct_4d().pack(_x.yaw, _x.pitch, _x.roll, _x.yawrate))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.imuData is None:
        self.imuData = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.imuData = []
      for i in range(0, length):
        val1 = rio_control_node.msg.IMU_Sensor_Data()
        _x = val1
        start = end
        end += 32
        (_x.yaw, _x.pitch, _x.roll, _x.yawrate,) = _get_struct_4d().unpack(str[start:end])
        self.imuData.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.imuData)
      buff.write(_struct_I.pack(length))
      for val1 in self.imuData:
        _x = val1
        buff.write(_get_struct_4d().pack(_x.yaw, _x.pitch, _x.roll, _x.yawrate))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.imuData is None:
        self.imuData = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.imuData = []
      for i in range(0, length):
        val1 = rio_control_node.msg.IMU_Sensor_Data()
        _x = val1
        start = end
        end += 32
        (_x.yaw, _x.pitch, _x.roll, _x.yawrate,) = _get_struct_4d().unpack(str[start:end])
        self.imuData.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
