# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rio_control_node/Motor_Control.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import rio_control_node.msg

class Motor_Control(genpy.Message):
  _md5sum = "3cf41406b72ffdc820cf64897de2fb84"
  _type = "rio_control_node/Motor_Control"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """Motor[] motors
================================================================================
MSG: rio_control_node/Motor
int8 TALON_FX = 0
int8 TALON_SRX = 1

int8 PERCENT_OUTPUT=0
int8 POSITION=1
int8 VELOCITY=2
int8 CURRENT=3
int8 FOLLOWER=5
int8 MOTION_PROFILE=6
int8 MOTION_MAGIC=7
int8 MOTION_PROFILE_ARC=10
int8 MUSIC_TONE=13
int8 DISABLED=15

int32 id
int8 controller_type
int8 control_mode
float64 output_value
float64 arbitrary_feedforward"""
  __slots__ = ['motors']
  _slot_types = ['rio_control_node/Motor[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       motors

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Motor_Control, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.motors is None:
        self.motors = []
    else:
      self.motors = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.motors)
      buff.write(_struct_I.pack(length))
      for val1 in self.motors:
        _x = val1
        buff.write(_get_struct_i2b2d().pack(_x.id, _x.controller_type, _x.control_mode, _x.output_value, _x.arbitrary_feedforward))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.motors is None:
        self.motors = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.motors = []
      for i in range(0, length):
        val1 = rio_control_node.msg.Motor()
        _x = val1
        start = end
        end += 22
        (_x.id, _x.controller_type, _x.control_mode, _x.output_value, _x.arbitrary_feedforward,) = _get_struct_i2b2d().unpack(str[start:end])
        self.motors.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.motors)
      buff.write(_struct_I.pack(length))
      for val1 in self.motors:
        _x = val1
        buff.write(_get_struct_i2b2d().pack(_x.id, _x.controller_type, _x.control_mode, _x.output_value, _x.arbitrary_feedforward))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.motors is None:
        self.motors = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.motors = []
      for i in range(0, length):
        val1 = rio_control_node.msg.Motor()
        _x = val1
        start = end
        end += 22
        (_x.id, _x.controller_type, _x.control_mode, _x.output_value, _x.arbitrary_feedforward,) = _get_struct_i2b2d().unpack(str[start:end])
        self.motors.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i2b2d = None
def _get_struct_i2b2d():
    global _struct_i2b2d
    if _struct_i2b2d is None:
        _struct_i2b2d = struct.Struct("<i2b2d")
    return _struct_i2b2d
