# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rio_control_node/Motor_Status.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import rio_control_node.msg

class Motor_Status(genpy.Message):
  _md5sum = "7d9d4a73ef78dcf618bf8682900ebfa5"
  _type = "rio_control_node/Motor_Status"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """Motor_Info[] motors
================================================================================
MSG: rio_control_node/Motor_Info
int8 PERCENT_OUTPUT=0
int8 POSITION=1
int8 VELOCITY=2
int8 CURRENT=3
int8 FOLLOWER=5
int8 MOTION_PROFILE=6
int8 MOTION_MAGIC=7
int8 MOTION_PROFILE_ARC=10
int8 MUSIC_TONE=13
int8 DISABLED=15

int32 id
float64 sensor_position
float64 sensor_velocity
float64 bus_voltage
float64 bus_current
float64 stator_current
bool forward_limit_closed
bool reverse_limit_closed
int8 control_mode
float64 commanded_output
float64 active_trajectory_arbff
float64 active_trajectory_position
float64 active_trajectory_velocity
float64 raw_closed_loop_error
float64 raw_integral_accum
float64 raw_error_derivative
float64 raw_output_percent"""
  __slots__ = ['motors']
  _slot_types = ['rio_control_node/Motor_Info[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       motors

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Motor_Status, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.motors is None:
        self.motors = []
    else:
      self.motors = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.motors)
      buff.write(_struct_I.pack(length))
      for val1 in self.motors:
        _x = val1
        buff.write(_get_struct_i5d2Bb8d().pack(_x.id, _x.sensor_position, _x.sensor_velocity, _x.bus_voltage, _x.bus_current, _x.stator_current, _x.forward_limit_closed, _x.reverse_limit_closed, _x.control_mode, _x.commanded_output, _x.active_trajectory_arbff, _x.active_trajectory_position, _x.active_trajectory_velocity, _x.raw_closed_loop_error, _x.raw_integral_accum, _x.raw_error_derivative, _x.raw_output_percent))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.motors is None:
        self.motors = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.motors = []
      for i in range(0, length):
        val1 = rio_control_node.msg.Motor_Info()
        _x = val1
        start = end
        end += 111
        (_x.id, _x.sensor_position, _x.sensor_velocity, _x.bus_voltage, _x.bus_current, _x.stator_current, _x.forward_limit_closed, _x.reverse_limit_closed, _x.control_mode, _x.commanded_output, _x.active_trajectory_arbff, _x.active_trajectory_position, _x.active_trajectory_velocity, _x.raw_closed_loop_error, _x.raw_integral_accum, _x.raw_error_derivative, _x.raw_output_percent,) = _get_struct_i5d2Bb8d().unpack(str[start:end])
        val1.forward_limit_closed = bool(val1.forward_limit_closed)
        val1.reverse_limit_closed = bool(val1.reverse_limit_closed)
        self.motors.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.motors)
      buff.write(_struct_I.pack(length))
      for val1 in self.motors:
        _x = val1
        buff.write(_get_struct_i5d2Bb8d().pack(_x.id, _x.sensor_position, _x.sensor_velocity, _x.bus_voltage, _x.bus_current, _x.stator_current, _x.forward_limit_closed, _x.reverse_limit_closed, _x.control_mode, _x.commanded_output, _x.active_trajectory_arbff, _x.active_trajectory_position, _x.active_trajectory_velocity, _x.raw_closed_loop_error, _x.raw_integral_accum, _x.raw_error_derivative, _x.raw_output_percent))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.motors is None:
        self.motors = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.motors = []
      for i in range(0, length):
        val1 = rio_control_node.msg.Motor_Info()
        _x = val1
        start = end
        end += 111
        (_x.id, _x.sensor_position, _x.sensor_velocity, _x.bus_voltage, _x.bus_current, _x.stator_current, _x.forward_limit_closed, _x.reverse_limit_closed, _x.control_mode, _x.commanded_output, _x.active_trajectory_arbff, _x.active_trajectory_position, _x.active_trajectory_velocity, _x.raw_closed_loop_error, _x.raw_integral_accum, _x.raw_error_derivative, _x.raw_output_percent,) = _get_struct_i5d2Bb8d().unpack(str[start:end])
        val1.forward_limit_closed = bool(val1.forward_limit_closed)
        val1.reverse_limit_closed = bool(val1.reverse_limit_closed)
        self.motors.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i5d2Bb8d = None
def _get_struct_i5d2Bb8d():
    global _struct_i5d2Bb8d
    if _struct_i5d2Bb8d is None:
        _struct_i5d2Bb8d = struct.Struct("<i5d2Bb8d")
    return _struct_i5d2Bb8d
