// Generated by gencpp from file rio_control_node/Encoder_Configuration.msg
// DO NOT EDIT!


#ifndef RIO_CONTROL_NODE_MESSAGE_ENCODER_CONFIGURATION_H
#define RIO_CONTROL_NODE_MESSAGE_ENCODER_CONFIGURATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <rio_control_node/Encoder_Config.h>

namespace rio_control_node
{
template <class ContainerAllocator>
struct Encoder_Configuration_
{
  typedef Encoder_Configuration_<ContainerAllocator> Type;

  Encoder_Configuration_()
    : encoders()  {
    }
  Encoder_Configuration_(const ContainerAllocator& _alloc)
    : encoders(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::rio_control_node::Encoder_Config_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::rio_control_node::Encoder_Config_<ContainerAllocator> >::other >  _encoders_type;
  _encoders_type encoders;





  typedef boost::shared_ptr< ::rio_control_node::Encoder_Configuration_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rio_control_node::Encoder_Configuration_<ContainerAllocator> const> ConstPtr;

}; // struct Encoder_Configuration_

typedef ::rio_control_node::Encoder_Configuration_<std::allocator<void> > Encoder_Configuration;

typedef boost::shared_ptr< ::rio_control_node::Encoder_Configuration > Encoder_ConfigurationPtr;
typedef boost::shared_ptr< ::rio_control_node::Encoder_Configuration const> Encoder_ConfigurationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rio_control_node::Encoder_Configuration_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rio_control_node::Encoder_Configuration_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rio_control_node::Encoder_Configuration_<ContainerAllocator1> & lhs, const ::rio_control_node::Encoder_Configuration_<ContainerAllocator2> & rhs)
{
  return lhs.encoders == rhs.encoders;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rio_control_node::Encoder_Configuration_<ContainerAllocator1> & lhs, const ::rio_control_node::Encoder_Configuration_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rio_control_node

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rio_control_node::Encoder_Configuration_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rio_control_node::Encoder_Configuration_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rio_control_node::Encoder_Configuration_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rio_control_node::Encoder_Configuration_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rio_control_node::Encoder_Configuration_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rio_control_node::Encoder_Configuration_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rio_control_node::Encoder_Configuration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cfaf2f7f74f1fe7617a6711b9661307b";
  }

  static const char* value(const ::rio_control_node::Encoder_Configuration_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcfaf2f7f74f1fe76ULL;
  static const uint64_t static_value2 = 0x17a6711b9661307bULL;
};

template<class ContainerAllocator>
struct DataType< ::rio_control_node::Encoder_Configuration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rio_control_node/Encoder_Configuration";
  }

  static const char* value(const ::rio_control_node::Encoder_Configuration_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rio_control_node::Encoder_Configuration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Encoder_Config[] encoders\n"
"================================================================================\n"
"MSG: rio_control_node/Encoder_Config\n"
"int8 CANCoder=0\n"
"\n"
"int8 ENCODERSOURCE_RELATIVE=0\n"
"int8 ENCODERSOURCE_ABSOLUTE=1\n"
"\n"
"int8 CAN_RIO_INTERNAL=0\n"
"int8 CAN_RIO_CANIVORE=1\n"
"int8 CAN_COPROCESSOR_CAN=2\n"
"\n"
"int32 id\n"
"int8 encoder_type\n"
"int8 sensor_source\n"
"int8 can_network\n"
;
  }

  static const char* value(const ::rio_control_node::Encoder_Configuration_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rio_control_node::Encoder_Configuration_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.encoders);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Encoder_Configuration_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rio_control_node::Encoder_Configuration_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rio_control_node::Encoder_Configuration_<ContainerAllocator>& v)
  {
    s << indent << "encoders[]" << std::endl;
    for (size_t i = 0; i < v.encoders.size(); ++i)
    {
      s << indent << "  encoders[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::rio_control_node::Encoder_Config_<ContainerAllocator> >::stream(s, indent + "    ", v.encoders[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RIO_CONTROL_NODE_MESSAGE_ENCODER_CONFIGURATION_H
