// Generated by gencpp from file rio_control_node/IMU_Sensor_Data.msg
// DO NOT EDIT!


#ifndef RIO_CONTROL_NODE_MESSAGE_IMU_SENSOR_DATA_H
#define RIO_CONTROL_NODE_MESSAGE_IMU_SENSOR_DATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rio_control_node
{
template <class ContainerAllocator>
struct IMU_Sensor_Data_
{
  typedef IMU_Sensor_Data_<ContainerAllocator> Type;

  IMU_Sensor_Data_()
    : yaw(0.0)
    , pitch(0.0)
    , roll(0.0)
    , yawrate(0.0)  {
    }
  IMU_Sensor_Data_(const ContainerAllocator& _alloc)
    : yaw(0.0)
    , pitch(0.0)
    , roll(0.0)
    , yawrate(0.0)  {
  (void)_alloc;
    }



   typedef double _yaw_type;
  _yaw_type yaw;

   typedef double _pitch_type;
  _pitch_type pitch;

   typedef double _roll_type;
  _roll_type roll;

   typedef double _yawrate_type;
  _yawrate_type yawrate;





  typedef boost::shared_ptr< ::rio_control_node::IMU_Sensor_Data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rio_control_node::IMU_Sensor_Data_<ContainerAllocator> const> ConstPtr;

}; // struct IMU_Sensor_Data_

typedef ::rio_control_node::IMU_Sensor_Data_<std::allocator<void> > IMU_Sensor_Data;

typedef boost::shared_ptr< ::rio_control_node::IMU_Sensor_Data > IMU_Sensor_DataPtr;
typedef boost::shared_ptr< ::rio_control_node::IMU_Sensor_Data const> IMU_Sensor_DataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rio_control_node::IMU_Sensor_Data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rio_control_node::IMU_Sensor_Data_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rio_control_node::IMU_Sensor_Data_<ContainerAllocator1> & lhs, const ::rio_control_node::IMU_Sensor_Data_<ContainerAllocator2> & rhs)
{
  return lhs.yaw == rhs.yaw &&
    lhs.pitch == rhs.pitch &&
    lhs.roll == rhs.roll &&
    lhs.yawrate == rhs.yawrate;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rio_control_node::IMU_Sensor_Data_<ContainerAllocator1> & lhs, const ::rio_control_node::IMU_Sensor_Data_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rio_control_node

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rio_control_node::IMU_Sensor_Data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rio_control_node::IMU_Sensor_Data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rio_control_node::IMU_Sensor_Data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rio_control_node::IMU_Sensor_Data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rio_control_node::IMU_Sensor_Data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rio_control_node::IMU_Sensor_Data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rio_control_node::IMU_Sensor_Data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c2a1555a077e8e85b8dff34f92cccd65";
  }

  static const char* value(const ::rio_control_node::IMU_Sensor_Data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc2a1555a077e8e85ULL;
  static const uint64_t static_value2 = 0xb8dff34f92cccd65ULL;
};

template<class ContainerAllocator>
struct DataType< ::rio_control_node::IMU_Sensor_Data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rio_control_node/IMU_Sensor_Data";
  }

  static const char* value(const ::rio_control_node::IMU_Sensor_Data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rio_control_node::IMU_Sensor_Data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 yaw\n"
"float64 pitch\n"
"float64 roll\n"
"float64 yawrate\n"
;
  }

  static const char* value(const ::rio_control_node::IMU_Sensor_Data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rio_control_node::IMU_Sensor_Data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.yaw);
      stream.next(m.pitch);
      stream.next(m.roll);
      stream.next(m.yawrate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IMU_Sensor_Data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rio_control_node::IMU_Sensor_Data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rio_control_node::IMU_Sensor_Data_<ContainerAllocator>& v)
  {
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "yawrate: ";
    Printer<double>::stream(s, indent + "  ", v.yawrate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RIO_CONTROL_NODE_MESSAGE_IMU_SENSOR_DATA_H
