// Generated by gencpp from file rio_control_node/Solenoid_Info.msg
// DO NOT EDIT!


#ifndef RIO_CONTROL_NODE_MESSAGE_SOLENOID_INFO_H
#define RIO_CONTROL_NODE_MESSAGE_SOLENOID_INFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rio_control_node
{
template <class ContainerAllocator>
struct Solenoid_Info_
{
  typedef Solenoid_Info_<ContainerAllocator> Type;

  Solenoid_Info_()
    : id(0)
    , solenoid_value(0)  {
    }
  Solenoid_Info_(const ContainerAllocator& _alloc)
    : id(0)
    , solenoid_value(0)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef int8_t _solenoid_value_type;
  _solenoid_value_type solenoid_value;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(OFF)
  #undef OFF
#endif
#if defined(_WIN32) && defined(ON)
  #undef ON
#endif
#if defined(_WIN32) && defined(FORWARD)
  #undef FORWARD
#endif
#if defined(_WIN32) && defined(REVERSE)
  #undef REVERSE
#endif

  enum {
    OFF = 0,
    ON = 1,
    FORWARD = 1,
    REVERSE = 2,
  };


  typedef boost::shared_ptr< ::rio_control_node::Solenoid_Info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rio_control_node::Solenoid_Info_<ContainerAllocator> const> ConstPtr;

}; // struct Solenoid_Info_

typedef ::rio_control_node::Solenoid_Info_<std::allocator<void> > Solenoid_Info;

typedef boost::shared_ptr< ::rio_control_node::Solenoid_Info > Solenoid_InfoPtr;
typedef boost::shared_ptr< ::rio_control_node::Solenoid_Info const> Solenoid_InfoConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rio_control_node::Solenoid_Info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rio_control_node::Solenoid_Info_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rio_control_node::Solenoid_Info_<ContainerAllocator1> & lhs, const ::rio_control_node::Solenoid_Info_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.solenoid_value == rhs.solenoid_value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rio_control_node::Solenoid_Info_<ContainerAllocator1> & lhs, const ::rio_control_node::Solenoid_Info_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rio_control_node

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rio_control_node::Solenoid_Info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rio_control_node::Solenoid_Info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rio_control_node::Solenoid_Info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rio_control_node::Solenoid_Info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rio_control_node::Solenoid_Info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rio_control_node::Solenoid_Info_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rio_control_node::Solenoid_Info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0b1b7635992c7303c9bd2f169ac05a56";
  }

  static const char* value(const ::rio_control_node::Solenoid_Info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0b1b7635992c7303ULL;
  static const uint64_t static_value2 = 0xc9bd2f169ac05a56ULL;
};

template<class ContainerAllocator>
struct DataType< ::rio_control_node::Solenoid_Info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rio_control_node/Solenoid_Info";
  }

  static const char* value(const ::rio_control_node::Solenoid_Info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rio_control_node::Solenoid_Info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 OFF = 0\n"
"int8 ON = 1\n"
"int8 FORWARD = 1\n"
"int8 REVERSE = 2\n"
"\n"
"int32 id\n"
"int8 solenoid_value\n"
;
  }

  static const char* value(const ::rio_control_node::Solenoid_Info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rio_control_node::Solenoid_Info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.solenoid_value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Solenoid_Info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rio_control_node::Solenoid_Info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rio_control_node::Solenoid_Info_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "solenoid_value: ";
    Printer<int8_t>::stream(s, indent + "  ", v.solenoid_value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RIO_CONTROL_NODE_MESSAGE_SOLENOID_INFO_H
