// Generated by gencpp from file rio_control_node/Solenoid_Control.msg
// DO NOT EDIT!


#ifndef RIO_CONTROL_NODE_MESSAGE_SOLENOID_CONTROL_H
#define RIO_CONTROL_NODE_MESSAGE_SOLENOID_CONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <rio_control_node/Solenoid.h>

namespace rio_control_node
{
template <class ContainerAllocator>
struct Solenoid_Control_
{
  typedef Solenoid_Control_<ContainerAllocator> Type;

  Solenoid_Control_()
    : solenoids()  {
    }
  Solenoid_Control_(const ContainerAllocator& _alloc)
    : solenoids(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::rio_control_node::Solenoid_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::rio_control_node::Solenoid_<ContainerAllocator> >::other >  _solenoids_type;
  _solenoids_type solenoids;





  typedef boost::shared_ptr< ::rio_control_node::Solenoid_Control_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rio_control_node::Solenoid_Control_<ContainerAllocator> const> ConstPtr;

}; // struct Solenoid_Control_

typedef ::rio_control_node::Solenoid_Control_<std::allocator<void> > Solenoid_Control;

typedef boost::shared_ptr< ::rio_control_node::Solenoid_Control > Solenoid_ControlPtr;
typedef boost::shared_ptr< ::rio_control_node::Solenoid_Control const> Solenoid_ControlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rio_control_node::Solenoid_Control_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rio_control_node::Solenoid_Control_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rio_control_node::Solenoid_Control_<ContainerAllocator1> & lhs, const ::rio_control_node::Solenoid_Control_<ContainerAllocator2> & rhs)
{
  return lhs.solenoids == rhs.solenoids;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rio_control_node::Solenoid_Control_<ContainerAllocator1> & lhs, const ::rio_control_node::Solenoid_Control_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rio_control_node

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rio_control_node::Solenoid_Control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rio_control_node::Solenoid_Control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rio_control_node::Solenoid_Control_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rio_control_node::Solenoid_Control_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rio_control_node::Solenoid_Control_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rio_control_node::Solenoid_Control_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rio_control_node::Solenoid_Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d1ee07b2cb998afb7fb1c3220604e07f";
  }

  static const char* value(const ::rio_control_node::Solenoid_Control_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd1ee07b2cb998afbULL;
  static const uint64_t static_value2 = 0x7fb1c3220604e07fULL;
};

template<class ContainerAllocator>
struct DataType< ::rio_control_node::Solenoid_Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rio_control_node/Solenoid_Control";
  }

  static const char* value(const ::rio_control_node::Solenoid_Control_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rio_control_node::Solenoid_Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Solenoid[] solenoids\n"
"================================================================================\n"
"MSG: rio_control_node/Solenoid\n"
"int8 SINGLE = 0\n"
"int8 DOUBLE = 1\n"
"\n"
"int8 CTREPCM = 0\n"
"int8 REVPH = 1\n"
"\n"
"int8 OFF = 0\n"
"int8 ON = 1\n"
"int8 FORWARD = 1\n"
"int8 REVERSE = 2\n"
"\n"
"int32 id\n"
"int8 solenoid_type\n"
"int8 module_type\n"
"int8 output_value\n"
;
  }

  static const char* value(const ::rio_control_node::Solenoid_Control_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rio_control_node::Solenoid_Control_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.solenoids);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Solenoid_Control_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rio_control_node::Solenoid_Control_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rio_control_node::Solenoid_Control_<ContainerAllocator>& v)
  {
    s << indent << "solenoids[]" << std::endl;
    for (size_t i = 0; i < v.solenoids.size(); ++i)
    {
      s << indent << "  solenoids[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::rio_control_node::Solenoid_<ContainerAllocator> >::stream(s, indent + "    ", v.solenoids[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RIO_CONTROL_NODE_MESSAGE_SOLENOID_CONTROL_H
