// Generated by gencpp from file network_tables_node/NTGetBool.msg
// DO NOT EDIT!


#ifndef NETWORK_TABLES_NODE_MESSAGE_NTGETBOOL_H
#define NETWORK_TABLES_NODE_MESSAGE_NTGETBOOL_H

#include <ros/service_traits.h>


#include <network_tables_node/NTGetBoolRequest.h>
#include <network_tables_node/NTGetBoolResponse.h>


namespace network_tables_node
{

struct NTGetBool
{

typedef NTGetBoolRequest Request;
typedef NTGetBoolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NTGetBool
} // namespace network_tables_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::network_tables_node::NTGetBool > {
  static const char* value()
  {
    return "13cb636e7a8fca94a5af54f315a6be34";
  }

  static const char* value(const ::network_tables_node::NTGetBool&) { return value(); }
};

template<>
struct DataType< ::network_tables_node::NTGetBool > {
  static const char* value()
  {
    return "network_tables_node/NTGetBool";
  }

  static const char* value(const ::network_tables_node::NTGetBool&) { return value(); }
};


// service_traits::MD5Sum< ::network_tables_node::NTGetBoolRequest> should match
// service_traits::MD5Sum< ::network_tables_node::NTGetBool >
template<>
struct MD5Sum< ::network_tables_node::NTGetBoolRequest>
{
  static const char* value()
  {
    return MD5Sum< ::network_tables_node::NTGetBool >::value();
  }
  static const char* value(const ::network_tables_node::NTGetBoolRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::network_tables_node::NTGetBoolRequest> should match
// service_traits::DataType< ::network_tables_node::NTGetBool >
template<>
struct DataType< ::network_tables_node::NTGetBoolRequest>
{
  static const char* value()
  {
    return DataType< ::network_tables_node::NTGetBool >::value();
  }
  static const char* value(const ::network_tables_node::NTGetBoolRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::network_tables_node::NTGetBoolResponse> should match
// service_traits::MD5Sum< ::network_tables_node::NTGetBool >
template<>
struct MD5Sum< ::network_tables_node::NTGetBoolResponse>
{
  static const char* value()
  {
    return MD5Sum< ::network_tables_node::NTGetBool >::value();
  }
  static const char* value(const ::network_tables_node::NTGetBoolResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::network_tables_node::NTGetBoolResponse> should match
// service_traits::DataType< ::network_tables_node::NTGetBool >
template<>
struct DataType< ::network_tables_node::NTGetBoolResponse>
{
  static const char* value()
  {
    return DataType< ::network_tables_node::NTGetBool >::value();
  }
  static const char* value(const ::network_tables_node::NTGetBoolResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NETWORK_TABLES_NODE_MESSAGE_NTGETBOOL_H
