// Generated by gencpp from file network_tables_node/NTGetDouble.msg
// DO NOT EDIT!


#ifndef NETWORK_TABLES_NODE_MESSAGE_NTGETDOUBLE_H
#define NETWORK_TABLES_NODE_MESSAGE_NTGETDOUBLE_H

#include <ros/service_traits.h>


#include <network_tables_node/NTGetDoubleRequest.h>
#include <network_tables_node/NTGetDoubleResponse.h>


namespace network_tables_node
{

struct NTGetDouble
{

typedef NTGetDoubleRequest Request;
typedef NTGetDoubleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NTGetDouble
} // namespace network_tables_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::network_tables_node::NTGetDouble > {
  static const char* value()
  {
    return "8b324ea25ce1a0fff01d97a04c768a10";
  }

  static const char* value(const ::network_tables_node::NTGetDouble&) { return value(); }
};

template<>
struct DataType< ::network_tables_node::NTGetDouble > {
  static const char* value()
  {
    return "network_tables_node/NTGetDouble";
  }

  static const char* value(const ::network_tables_node::NTGetDouble&) { return value(); }
};


// service_traits::MD5Sum< ::network_tables_node::NTGetDoubleRequest> should match
// service_traits::MD5Sum< ::network_tables_node::NTGetDouble >
template<>
struct MD5Sum< ::network_tables_node::NTGetDoubleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::network_tables_node::NTGetDouble >::value();
  }
  static const char* value(const ::network_tables_node::NTGetDoubleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::network_tables_node::NTGetDoubleRequest> should match
// service_traits::DataType< ::network_tables_node::NTGetDouble >
template<>
struct DataType< ::network_tables_node::NTGetDoubleRequest>
{
  static const char* value()
  {
    return DataType< ::network_tables_node::NTGetDouble >::value();
  }
  static const char* value(const ::network_tables_node::NTGetDoubleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::network_tables_node::NTGetDoubleResponse> should match
// service_traits::MD5Sum< ::network_tables_node::NTGetDouble >
template<>
struct MD5Sum< ::network_tables_node::NTGetDoubleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::network_tables_node::NTGetDouble >::value();
  }
  static const char* value(const ::network_tables_node::NTGetDoubleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::network_tables_node::NTGetDoubleResponse> should match
// service_traits::DataType< ::network_tables_node::NTGetDouble >
template<>
struct DataType< ::network_tables_node::NTGetDoubleResponse>
{
  static const char* value()
  {
    return DataType< ::network_tables_node::NTGetDouble >::value();
  }
  static const char* value(const ::network_tables_node::NTGetDoubleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NETWORK_TABLES_NODE_MESSAGE_NTGETDOUBLE_H
