// Generated by gencpp from file network_tables_node/NTGetString.msg
// DO NOT EDIT!


#ifndef NETWORK_TABLES_NODE_MESSAGE_NTGETSTRING_H
#define NETWORK_TABLES_NODE_MESSAGE_NTGETSTRING_H

#include <ros/service_traits.h>


#include <network_tables_node/NTGetStringRequest.h>
#include <network_tables_node/NTGetStringResponse.h>


namespace network_tables_node
{

struct NTGetString
{

typedef NTGetStringRequest Request;
typedef NTGetStringResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NTGetString
} // namespace network_tables_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::network_tables_node::NTGetString > {
  static const char* value()
  {
    return "5cc04fd552fedfa48e470913757b4777";
  }

  static const char* value(const ::network_tables_node::NTGetString&) { return value(); }
};

template<>
struct DataType< ::network_tables_node::NTGetString > {
  static const char* value()
  {
    return "network_tables_node/NTGetString";
  }

  static const char* value(const ::network_tables_node::NTGetString&) { return value(); }
};


// service_traits::MD5Sum< ::network_tables_node::NTGetStringRequest> should match
// service_traits::MD5Sum< ::network_tables_node::NTGetString >
template<>
struct MD5Sum< ::network_tables_node::NTGetStringRequest>
{
  static const char* value()
  {
    return MD5Sum< ::network_tables_node::NTGetString >::value();
  }
  static const char* value(const ::network_tables_node::NTGetStringRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::network_tables_node::NTGetStringRequest> should match
// service_traits::DataType< ::network_tables_node::NTGetString >
template<>
struct DataType< ::network_tables_node::NTGetStringRequest>
{
  static const char* value()
  {
    return DataType< ::network_tables_node::NTGetString >::value();
  }
  static const char* value(const ::network_tables_node::NTGetStringRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::network_tables_node::NTGetStringResponse> should match
// service_traits::MD5Sum< ::network_tables_node::NTGetString >
template<>
struct MD5Sum< ::network_tables_node::NTGetStringResponse>
{
  static const char* value()
  {
    return MD5Sum< ::network_tables_node::NTGetString >::value();
  }
  static const char* value(const ::network_tables_node::NTGetStringResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::network_tables_node::NTGetStringResponse> should match
// service_traits::DataType< ::network_tables_node::NTGetString >
template<>
struct DataType< ::network_tables_node::NTGetStringResponse>
{
  static const char* value()
  {
    return DataType< ::network_tables_node::NTGetString >::value();
  }
  static const char* value(const ::network_tables_node::NTGetStringResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NETWORK_TABLES_NODE_MESSAGE_NTGETSTRING_H
