// Generated by gencpp from file network_tables_node/NTGetRawResponse.msg
// DO NOT EDIT!


#ifndef NETWORK_TABLES_NODE_MESSAGE_NTGETRAWRESPONSE_H
#define NETWORK_TABLES_NODE_MESSAGE_NTGETRAWRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace network_tables_node
{
template <class ContainerAllocator>
struct NTGetRawResponse_
{
  typedef NTGetRawResponse_<ContainerAllocator> Type;

  NTGetRawResponse_()
    : output()
    , last_valid()  {
    }
  NTGetRawResponse_(const ContainerAllocator& _alloc)
    : output(_alloc)
    , last_valid()  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _output_type;
  _output_type output;

   typedef ros::Time _last_valid_type;
  _last_valid_type last_valid;





  typedef boost::shared_ptr< ::network_tables_node::NTGetRawResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::network_tables_node::NTGetRawResponse_<ContainerAllocator> const> ConstPtr;

}; // struct NTGetRawResponse_

typedef ::network_tables_node::NTGetRawResponse_<std::allocator<void> > NTGetRawResponse;

typedef boost::shared_ptr< ::network_tables_node::NTGetRawResponse > NTGetRawResponsePtr;
typedef boost::shared_ptr< ::network_tables_node::NTGetRawResponse const> NTGetRawResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::network_tables_node::NTGetRawResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::network_tables_node::NTGetRawResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::network_tables_node::NTGetRawResponse_<ContainerAllocator1> & lhs, const ::network_tables_node::NTGetRawResponse_<ContainerAllocator2> & rhs)
{
  return lhs.output == rhs.output &&
    lhs.last_valid == rhs.last_valid;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::network_tables_node::NTGetRawResponse_<ContainerAllocator1> & lhs, const ::network_tables_node::NTGetRawResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace network_tables_node

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::network_tables_node::NTGetRawResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::network_tables_node::NTGetRawResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::network_tables_node::NTGetRawResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::network_tables_node::NTGetRawResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::network_tables_node::NTGetRawResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::network_tables_node::NTGetRawResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::network_tables_node::NTGetRawResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9be683adffe8f6c4e9dfe54179d29426";
  }

  static const char* value(const ::network_tables_node::NTGetRawResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9be683adffe8f6c4ULL;
  static const uint64_t static_value2 = 0xe9dfe54179d29426ULL;
};

template<class ContainerAllocator>
struct DataType< ::network_tables_node::NTGetRawResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "network_tables_node/NTGetRawResponse";
  }

  static const char* value(const ::network_tables_node::NTGetRawResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::network_tables_node::NTGetRawResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Outputs\n"
"string output\n"
"time last_valid\n"
;
  }

  static const char* value(const ::network_tables_node::NTGetRawResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::network_tables_node::NTGetRawResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.output);
      stream.next(m.last_valid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NTGetRawResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::network_tables_node::NTGetRawResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::network_tables_node::NTGetRawResponse_<ContainerAllocator>& v)
  {
    s << indent << "output: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.output);
    s << indent << "last_valid: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.last_valid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NETWORK_TABLES_NODE_MESSAGE_NTGETRAWRESPONSE_H
