// Generated by gencpp from file network_tables_node/NTGetDoubleArrayRequest.msg
// DO NOT EDIT!


#ifndef NETWORK_TABLES_NODE_MESSAGE_NTGETDOUBLEARRAYREQUEST_H
#define NETWORK_TABLES_NODE_MESSAGE_NTGETDOUBLEARRAYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace network_tables_node
{
template <class ContainerAllocator>
struct NTGetDoubleArrayRequest_
{
  typedef NTGetDoubleArrayRequest_<ContainerAllocator> Type;

  NTGetDoubleArrayRequest_()
    : table_name()
    , entry_name()
    , default_value()  {
    }
  NTGetDoubleArrayRequest_(const ContainerAllocator& _alloc)
    : table_name(_alloc)
    , entry_name(_alloc)
    , default_value(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _table_name_type;
  _table_name_type table_name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _entry_name_type;
  _entry_name_type entry_name;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _default_value_type;
  _default_value_type default_value;





  typedef boost::shared_ptr< ::network_tables_node::NTGetDoubleArrayRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::network_tables_node::NTGetDoubleArrayRequest_<ContainerAllocator> const> ConstPtr;

}; // struct NTGetDoubleArrayRequest_

typedef ::network_tables_node::NTGetDoubleArrayRequest_<std::allocator<void> > NTGetDoubleArrayRequest;

typedef boost::shared_ptr< ::network_tables_node::NTGetDoubleArrayRequest > NTGetDoubleArrayRequestPtr;
typedef boost::shared_ptr< ::network_tables_node::NTGetDoubleArrayRequest const> NTGetDoubleArrayRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::network_tables_node::NTGetDoubleArrayRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::network_tables_node::NTGetDoubleArrayRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::network_tables_node::NTGetDoubleArrayRequest_<ContainerAllocator1> & lhs, const ::network_tables_node::NTGetDoubleArrayRequest_<ContainerAllocator2> & rhs)
{
  return lhs.table_name == rhs.table_name &&
    lhs.entry_name == rhs.entry_name &&
    lhs.default_value == rhs.default_value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::network_tables_node::NTGetDoubleArrayRequest_<ContainerAllocator1> & lhs, const ::network_tables_node::NTGetDoubleArrayRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace network_tables_node

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::network_tables_node::NTGetDoubleArrayRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::network_tables_node::NTGetDoubleArrayRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::network_tables_node::NTGetDoubleArrayRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::network_tables_node::NTGetDoubleArrayRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::network_tables_node::NTGetDoubleArrayRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::network_tables_node::NTGetDoubleArrayRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::network_tables_node::NTGetDoubleArrayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb3657734ac4c8aa707272c0c75883a3";
  }

  static const char* value(const ::network_tables_node::NTGetDoubleArrayRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb3657734ac4c8aaULL;
  static const uint64_t static_value2 = 0x707272c0c75883a3ULL;
};

template<class ContainerAllocator>
struct DataType< ::network_tables_node::NTGetDoubleArrayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "network_tables_node/NTGetDoubleArrayRequest";
  }

  static const char* value(const ::network_tables_node::NTGetDoubleArrayRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::network_tables_node::NTGetDoubleArrayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Inputs\n"
"string table_name\n"
"string entry_name\n"
"float64[] default_value\n"
;
  }

  static const char* value(const ::network_tables_node::NTGetDoubleArrayRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::network_tables_node::NTGetDoubleArrayRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.table_name);
      stream.next(m.entry_name);
      stream.next(m.default_value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NTGetDoubleArrayRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::network_tables_node::NTGetDoubleArrayRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::network_tables_node::NTGetDoubleArrayRequest_<ContainerAllocator>& v)
  {
    s << indent << "table_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.table_name);
    s << indent << "entry_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.entry_name);
    s << indent << "default_value[]" << std::endl;
    for (size_t i = 0; i < v.default_value.size(); ++i)
    {
      s << indent << "  default_value[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.default_value[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NETWORK_TABLES_NODE_MESSAGE_NTGETDOUBLEARRAYREQUEST_H
