// Generated by gencpp from file network_tables_node/NTGetDoubleArray.msg
// DO NOT EDIT!


#ifndef NETWORK_TABLES_NODE_MESSAGE_NTGETDOUBLEARRAY_H
#define NETWORK_TABLES_NODE_MESSAGE_NTGETDOUBLEARRAY_H

#include <ros/service_traits.h>


#include <network_tables_node/NTGetDoubleArrayRequest.h>
#include <network_tables_node/NTGetDoubleArrayResponse.h>


namespace network_tables_node
{

struct NTGetDoubleArray
{

typedef NTGetDoubleArrayRequest Request;
typedef NTGetDoubleArrayResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NTGetDoubleArray
} // namespace network_tables_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::network_tables_node::NTGetDoubleArray > {
  static const char* value()
  {
    return "2384401dfebab01dd59a440974811a03";
  }

  static const char* value(const ::network_tables_node::NTGetDoubleArray&) { return value(); }
};

template<>
struct DataType< ::network_tables_node::NTGetDoubleArray > {
  static const char* value()
  {
    return "network_tables_node/NTGetDoubleArray";
  }

  static const char* value(const ::network_tables_node::NTGetDoubleArray&) { return value(); }
};


// service_traits::MD5Sum< ::network_tables_node::NTGetDoubleArrayRequest> should match
// service_traits::MD5Sum< ::network_tables_node::NTGetDoubleArray >
template<>
struct MD5Sum< ::network_tables_node::NTGetDoubleArrayRequest>
{
  static const char* value()
  {
    return MD5Sum< ::network_tables_node::NTGetDoubleArray >::value();
  }
  static const char* value(const ::network_tables_node::NTGetDoubleArrayRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::network_tables_node::NTGetDoubleArrayRequest> should match
// service_traits::DataType< ::network_tables_node::NTGetDoubleArray >
template<>
struct DataType< ::network_tables_node::NTGetDoubleArrayRequest>
{
  static const char* value()
  {
    return DataType< ::network_tables_node::NTGetDoubleArray >::value();
  }
  static const char* value(const ::network_tables_node::NTGetDoubleArrayRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::network_tables_node::NTGetDoubleArrayResponse> should match
// service_traits::MD5Sum< ::network_tables_node::NTGetDoubleArray >
template<>
struct MD5Sum< ::network_tables_node::NTGetDoubleArrayResponse>
{
  static const char* value()
  {
    return MD5Sum< ::network_tables_node::NTGetDoubleArray >::value();
  }
  static const char* value(const ::network_tables_node::NTGetDoubleArrayResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::network_tables_node::NTGetDoubleArrayResponse> should match
// service_traits::DataType< ::network_tables_node::NTGetDoubleArray >
template<>
struct DataType< ::network_tables_node::NTGetDoubleArrayResponse>
{
  static const char* value()
  {
    return DataType< ::network_tables_node::NTGetDoubleArray >::value();
  }
  static const char* value(const ::network_tables_node::NTGetDoubleArrayResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NETWORK_TABLES_NODE_MESSAGE_NTGETDOUBLEARRAY_H
