// Generated by gencpp from file network_tables_node/NTGetBoolArrayResponse.msg
// DO NOT EDIT!


#ifndef NETWORK_TABLES_NODE_MESSAGE_NTGETBOOLARRAYRESPONSE_H
#define NETWORK_TABLES_NODE_MESSAGE_NTGETBOOLARRAYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace network_tables_node
{
template <class ContainerAllocator>
struct NTGetBoolArrayResponse_
{
  typedef NTGetBoolArrayResponse_<ContainerAllocator> Type;

  NTGetBoolArrayResponse_()
    : output()
    , last_valid()  {
    }
  NTGetBoolArrayResponse_(const ContainerAllocator& _alloc)
    : output(_alloc)
    , last_valid()  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _output_type;
  _output_type output;

   typedef ros::Time _last_valid_type;
  _last_valid_type last_valid;





  typedef boost::shared_ptr< ::network_tables_node::NTGetBoolArrayResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::network_tables_node::NTGetBoolArrayResponse_<ContainerAllocator> const> ConstPtr;

}; // struct NTGetBoolArrayResponse_

typedef ::network_tables_node::NTGetBoolArrayResponse_<std::allocator<void> > NTGetBoolArrayResponse;

typedef boost::shared_ptr< ::network_tables_node::NTGetBoolArrayResponse > NTGetBoolArrayResponsePtr;
typedef boost::shared_ptr< ::network_tables_node::NTGetBoolArrayResponse const> NTGetBoolArrayResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::network_tables_node::NTGetBoolArrayResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::network_tables_node::NTGetBoolArrayResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::network_tables_node::NTGetBoolArrayResponse_<ContainerAllocator1> & lhs, const ::network_tables_node::NTGetBoolArrayResponse_<ContainerAllocator2> & rhs)
{
  return lhs.output == rhs.output &&
    lhs.last_valid == rhs.last_valid;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::network_tables_node::NTGetBoolArrayResponse_<ContainerAllocator1> & lhs, const ::network_tables_node::NTGetBoolArrayResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace network_tables_node

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::network_tables_node::NTGetBoolArrayResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::network_tables_node::NTGetBoolArrayResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::network_tables_node::NTGetBoolArrayResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::network_tables_node::NTGetBoolArrayResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::network_tables_node::NTGetBoolArrayResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::network_tables_node::NTGetBoolArrayResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::network_tables_node::NTGetBoolArrayResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "752e85a17676d7fd0ece900f957f8682";
  }

  static const char* value(const ::network_tables_node::NTGetBoolArrayResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x752e85a17676d7fdULL;
  static const uint64_t static_value2 = 0x0ece900f957f8682ULL;
};

template<class ContainerAllocator>
struct DataType< ::network_tables_node::NTGetBoolArrayResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "network_tables_node/NTGetBoolArrayResponse";
  }

  static const char* value(const ::network_tables_node::NTGetBoolArrayResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::network_tables_node::NTGetBoolArrayResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Outputs\n"
"bool[] output\n"
"time last_valid\n"
;
  }

  static const char* value(const ::network_tables_node::NTGetBoolArrayResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::network_tables_node::NTGetBoolArrayResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.output);
      stream.next(m.last_valid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NTGetBoolArrayResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::network_tables_node::NTGetBoolArrayResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::network_tables_node::NTGetBoolArrayResponse_<ContainerAllocator>& v)
  {
    s << indent << "output[]" << std::endl;
    for (size_t i = 0; i < v.output.size(); ++i)
    {
      s << indent << "  output[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.output[i]);
    }
    s << indent << "last_valid: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.last_valid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NETWORK_TABLES_NODE_MESSAGE_NTGETBOOLARRAYRESPONSE_H
