// Generated by gencpp from file network_tables_node/NTGetBoolArray.msg
// DO NOT EDIT!


#ifndef NETWORK_TABLES_NODE_MESSAGE_NTGETBOOLARRAY_H
#define NETWORK_TABLES_NODE_MESSAGE_NTGETBOOLARRAY_H

#include <ros/service_traits.h>


#include <network_tables_node/NTGetBoolArrayRequest.h>
#include <network_tables_node/NTGetBoolArrayResponse.h>


namespace network_tables_node
{

struct NTGetBoolArray
{

typedef NTGetBoolArrayRequest Request;
typedef NTGetBoolArrayResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NTGetBoolArray
} // namespace network_tables_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::network_tables_node::NTGetBoolArray > {
  static const char* value()
  {
    return "6bab245b1a2646c56c1f1e756a56cf3e";
  }

  static const char* value(const ::network_tables_node::NTGetBoolArray&) { return value(); }
};

template<>
struct DataType< ::network_tables_node::NTGetBoolArray > {
  static const char* value()
  {
    return "network_tables_node/NTGetBoolArray";
  }

  static const char* value(const ::network_tables_node::NTGetBoolArray&) { return value(); }
};


// service_traits::MD5Sum< ::network_tables_node::NTGetBoolArrayRequest> should match
// service_traits::MD5Sum< ::network_tables_node::NTGetBoolArray >
template<>
struct MD5Sum< ::network_tables_node::NTGetBoolArrayRequest>
{
  static const char* value()
  {
    return MD5Sum< ::network_tables_node::NTGetBoolArray >::value();
  }
  static const char* value(const ::network_tables_node::NTGetBoolArrayRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::network_tables_node::NTGetBoolArrayRequest> should match
// service_traits::DataType< ::network_tables_node::NTGetBoolArray >
template<>
struct DataType< ::network_tables_node::NTGetBoolArrayRequest>
{
  static const char* value()
  {
    return DataType< ::network_tables_node::NTGetBoolArray >::value();
  }
  static const char* value(const ::network_tables_node::NTGetBoolArrayRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::network_tables_node::NTGetBoolArrayResponse> should match
// service_traits::MD5Sum< ::network_tables_node::NTGetBoolArray >
template<>
struct MD5Sum< ::network_tables_node::NTGetBoolArrayResponse>
{
  static const char* value()
  {
    return MD5Sum< ::network_tables_node::NTGetBoolArray >::value();
  }
  static const char* value(const ::network_tables_node::NTGetBoolArrayResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::network_tables_node::NTGetBoolArrayResponse> should match
// service_traits::DataType< ::network_tables_node::NTGetBoolArray >
template<>
struct DataType< ::network_tables_node::NTGetBoolArrayResponse>
{
  static const char* value()
  {
    return DataType< ::network_tables_node::NTGetBoolArray >::value();
  }
  static const char* value(const ::network_tables_node::NTGetBoolArrayResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NETWORK_TABLES_NODE_MESSAGE_NTGETBOOLARRAY_H
