// Generated by gencpp from file network_tables_node/NTGetRaw.msg
// DO NOT EDIT!


#ifndef NETWORK_TABLES_NODE_MESSAGE_NTGETRAW_H
#define NETWORK_TABLES_NODE_MESSAGE_NTGETRAW_H

#include <ros/service_traits.h>


#include <network_tables_node/NTGetRawRequest.h>
#include <network_tables_node/NTGetRawResponse.h>


namespace network_tables_node
{

struct NTGetRaw
{

typedef NTGetRawRequest Request;
typedef NTGetRawResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NTGetRaw
} // namespace network_tables_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::network_tables_node::NTGetRaw > {
  static const char* value()
  {
    return "5cc04fd552fedfa48e470913757b4777";
  }

  static const char* value(const ::network_tables_node::NTGetRaw&) { return value(); }
};

template<>
struct DataType< ::network_tables_node::NTGetRaw > {
  static const char* value()
  {
    return "network_tables_node/NTGetRaw";
  }

  static const char* value(const ::network_tables_node::NTGetRaw&) { return value(); }
};


// service_traits::MD5Sum< ::network_tables_node::NTGetRawRequest> should match
// service_traits::MD5Sum< ::network_tables_node::NTGetRaw >
template<>
struct MD5Sum< ::network_tables_node::NTGetRawRequest>
{
  static const char* value()
  {
    return MD5Sum< ::network_tables_node::NTGetRaw >::value();
  }
  static const char* value(const ::network_tables_node::NTGetRawRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::network_tables_node::NTGetRawRequest> should match
// service_traits::DataType< ::network_tables_node::NTGetRaw >
template<>
struct DataType< ::network_tables_node::NTGetRawRequest>
{
  static const char* value()
  {
    return DataType< ::network_tables_node::NTGetRaw >::value();
  }
  static const char* value(const ::network_tables_node::NTGetRawRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::network_tables_node::NTGetRawResponse> should match
// service_traits::MD5Sum< ::network_tables_node::NTGetRaw >
template<>
struct MD5Sum< ::network_tables_node::NTGetRawResponse>
{
  static const char* value()
  {
    return MD5Sum< ::network_tables_node::NTGetRaw >::value();
  }
  static const char* value(const ::network_tables_node::NTGetRawResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::network_tables_node::NTGetRawResponse> should match
// service_traits::DataType< ::network_tables_node::NTGetRaw >
template<>
struct DataType< ::network_tables_node::NTGetRawResponse>
{
  static const char* value()
  {
    return DataType< ::network_tables_node::NTGetRaw >::value();
  }
  static const char* value(const ::network_tables_node::NTGetRawResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NETWORK_TABLES_NODE_MESSAGE_NTGETRAW_H
