// Generated by gencpp from file network_tables_node/NTGetStringArray.msg
// DO NOT EDIT!


#ifndef NETWORK_TABLES_NODE_MESSAGE_NTGETSTRINGARRAY_H
#define NETWORK_TABLES_NODE_MESSAGE_NTGETSTRINGARRAY_H

#include <ros/service_traits.h>


#include <network_tables_node/NTGetStringArrayRequest.h>
#include <network_tables_node/NTGetStringArrayResponse.h>


namespace network_tables_node
{

struct NTGetStringArray
{

typedef NTGetStringArrayRequest Request;
typedef NTGetStringArrayResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NTGetStringArray
} // namespace network_tables_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::network_tables_node::NTGetStringArray > {
  static const char* value()
  {
    return "ab18819313105b6cf38e945ab45be437";
  }

  static const char* value(const ::network_tables_node::NTGetStringArray&) { return value(); }
};

template<>
struct DataType< ::network_tables_node::NTGetStringArray > {
  static const char* value()
  {
    return "network_tables_node/NTGetStringArray";
  }

  static const char* value(const ::network_tables_node::NTGetStringArray&) { return value(); }
};


// service_traits::MD5Sum< ::network_tables_node::NTGetStringArrayRequest> should match
// service_traits::MD5Sum< ::network_tables_node::NTGetStringArray >
template<>
struct MD5Sum< ::network_tables_node::NTGetStringArrayRequest>
{
  static const char* value()
  {
    return MD5Sum< ::network_tables_node::NTGetStringArray >::value();
  }
  static const char* value(const ::network_tables_node::NTGetStringArrayRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::network_tables_node::NTGetStringArrayRequest> should match
// service_traits::DataType< ::network_tables_node::NTGetStringArray >
template<>
struct DataType< ::network_tables_node::NTGetStringArrayRequest>
{
  static const char* value()
  {
    return DataType< ::network_tables_node::NTGetStringArray >::value();
  }
  static const char* value(const ::network_tables_node::NTGetStringArrayRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::network_tables_node::NTGetStringArrayResponse> should match
// service_traits::MD5Sum< ::network_tables_node::NTGetStringArray >
template<>
struct MD5Sum< ::network_tables_node::NTGetStringArrayResponse>
{
  static const char* value()
  {
    return MD5Sum< ::network_tables_node::NTGetStringArray >::value();
  }
  static const char* value(const ::network_tables_node::NTGetStringArrayResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::network_tables_node::NTGetStringArrayResponse> should match
// service_traits::DataType< ::network_tables_node::NTGetStringArray >
template<>
struct DataType< ::network_tables_node::NTGetStringArrayResponse>
{
  static const char* value()
  {
    return DataType< ::network_tables_node::NTGetStringArray >::value();
  }
  static const char* value(const ::network_tables_node::NTGetStringArrayResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NETWORK_TABLES_NODE_MESSAGE_NTGETSTRINGARRAY_H
