// Generated by gencpp from file network_tables_node/NTGetDoubleRequest.msg
// DO NOT EDIT!


#ifndef NETWORK_TABLES_NODE_MESSAGE_NTGETDOUBLEREQUEST_H
#define NETWORK_TABLES_NODE_MESSAGE_NTGETDOUBLEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace network_tables_node
{
template <class ContainerAllocator>
struct NTGetDoubleRequest_
{
  typedef NTGetDoubleRequest_<ContainerAllocator> Type;

  NTGetDoubleRequest_()
    : table_name()
    , entry_name()
    , default_value(0.0)  {
    }
  NTGetDoubleRequest_(const ContainerAllocator& _alloc)
    : table_name(_alloc)
    , entry_name(_alloc)
    , default_value(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _table_name_type;
  _table_name_type table_name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _entry_name_type;
  _entry_name_type entry_name;

   typedef double _default_value_type;
  _default_value_type default_value;





  typedef boost::shared_ptr< ::network_tables_node::NTGetDoubleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::network_tables_node::NTGetDoubleRequest_<ContainerAllocator> const> ConstPtr;

}; // struct NTGetDoubleRequest_

typedef ::network_tables_node::NTGetDoubleRequest_<std::allocator<void> > NTGetDoubleRequest;

typedef boost::shared_ptr< ::network_tables_node::NTGetDoubleRequest > NTGetDoubleRequestPtr;
typedef boost::shared_ptr< ::network_tables_node::NTGetDoubleRequest const> NTGetDoubleRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::network_tables_node::NTGetDoubleRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::network_tables_node::NTGetDoubleRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::network_tables_node::NTGetDoubleRequest_<ContainerAllocator1> & lhs, const ::network_tables_node::NTGetDoubleRequest_<ContainerAllocator2> & rhs)
{
  return lhs.table_name == rhs.table_name &&
    lhs.entry_name == rhs.entry_name &&
    lhs.default_value == rhs.default_value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::network_tables_node::NTGetDoubleRequest_<ContainerAllocator1> & lhs, const ::network_tables_node::NTGetDoubleRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace network_tables_node

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::network_tables_node::NTGetDoubleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::network_tables_node::NTGetDoubleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::network_tables_node::NTGetDoubleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::network_tables_node::NTGetDoubleRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::network_tables_node::NTGetDoubleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::network_tables_node::NTGetDoubleRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::network_tables_node::NTGetDoubleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d00279eeeeb7df2f0e28097d372d181b";
  }

  static const char* value(const ::network_tables_node::NTGetDoubleRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd00279eeeeb7df2fULL;
  static const uint64_t static_value2 = 0x0e28097d372d181bULL;
};

template<class ContainerAllocator>
struct DataType< ::network_tables_node::NTGetDoubleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "network_tables_node/NTGetDoubleRequest";
  }

  static const char* value(const ::network_tables_node::NTGetDoubleRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::network_tables_node::NTGetDoubleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Inputs\n"
"string table_name\n"
"string entry_name\n"
"float64 default_value\n"
;
  }

  static const char* value(const ::network_tables_node::NTGetDoubleRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::network_tables_node::NTGetDoubleRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.table_name);
      stream.next(m.entry_name);
      stream.next(m.default_value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NTGetDoubleRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::network_tables_node::NTGetDoubleRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::network_tables_node::NTGetDoubleRequest_<ContainerAllocator>& v)
  {
    s << indent << "table_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.table_name);
    s << indent << "entry_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.entry_name);
    s << indent << "default_value: ";
    Printer<double>::stream(s, indent + "  ", v.default_value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NETWORK_TABLES_NODE_MESSAGE_NTGETDOUBLEREQUEST_H
