// Generated by gencpp from file network_tables_node/NTSetString.msg
// DO NOT EDIT!


#ifndef NETWORK_TABLES_NODE_MESSAGE_NTSETSTRING_H
#define NETWORK_TABLES_NODE_MESSAGE_NTSETSTRING_H

#include <ros/service_traits.h>


#include <network_tables_node/NTSetStringRequest.h>
#include <network_tables_node/NTSetStringResponse.h>


namespace network_tables_node
{

struct NTSetString
{

typedef NTSetStringRequest Request;
typedef NTSetStringResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NTSetString
} // namespace network_tables_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::network_tables_node::NTSetString > {
  static const char* value()
  {
    return "dc533d14351660a9df0803ae4ce0d5ae";
  }

  static const char* value(const ::network_tables_node::NTSetString&) { return value(); }
};

template<>
struct DataType< ::network_tables_node::NTSetString > {
  static const char* value()
  {
    return "network_tables_node/NTSetString";
  }

  static const char* value(const ::network_tables_node::NTSetString&) { return value(); }
};


// service_traits::MD5Sum< ::network_tables_node::NTSetStringRequest> should match
// service_traits::MD5Sum< ::network_tables_node::NTSetString >
template<>
struct MD5Sum< ::network_tables_node::NTSetStringRequest>
{
  static const char* value()
  {
    return MD5Sum< ::network_tables_node::NTSetString >::value();
  }
  static const char* value(const ::network_tables_node::NTSetStringRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::network_tables_node::NTSetStringRequest> should match
// service_traits::DataType< ::network_tables_node::NTSetString >
template<>
struct DataType< ::network_tables_node::NTSetStringRequest>
{
  static const char* value()
  {
    return DataType< ::network_tables_node::NTSetString >::value();
  }
  static const char* value(const ::network_tables_node::NTSetStringRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::network_tables_node::NTSetStringResponse> should match
// service_traits::MD5Sum< ::network_tables_node::NTSetString >
template<>
struct MD5Sum< ::network_tables_node::NTSetStringResponse>
{
  static const char* value()
  {
    return MD5Sum< ::network_tables_node::NTSetString >::value();
  }
  static const char* value(const ::network_tables_node::NTSetStringResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::network_tables_node::NTSetStringResponse> should match
// service_traits::DataType< ::network_tables_node::NTSetString >
template<>
struct DataType< ::network_tables_node::NTSetStringResponse>
{
  static const char* value()
  {
    return DataType< ::network_tables_node::NTSetString >::value();
  }
  static const char* value(const ::network_tables_node::NTSetStringResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NETWORK_TABLES_NODE_MESSAGE_NTSETSTRING_H
