// Generated by gencpp from file network_tables_node/NTSetRaw.msg
// DO NOT EDIT!


#ifndef NETWORK_TABLES_NODE_MESSAGE_NTSETRAW_H
#define NETWORK_TABLES_NODE_MESSAGE_NTSETRAW_H

#include <ros/service_traits.h>


#include <network_tables_node/NTSetRawRequest.h>
#include <network_tables_node/NTSetRawResponse.h>


namespace network_tables_node
{

struct NTSetRaw
{

typedef NTSetRawRequest Request;
typedef NTSetRawResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NTSetRaw
} // namespace network_tables_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::network_tables_node::NTSetRaw > {
  static const char* value()
  {
    return "dc533d14351660a9df0803ae4ce0d5ae";
  }

  static const char* value(const ::network_tables_node::NTSetRaw&) { return value(); }
};

template<>
struct DataType< ::network_tables_node::NTSetRaw > {
  static const char* value()
  {
    return "network_tables_node/NTSetRaw";
  }

  static const char* value(const ::network_tables_node::NTSetRaw&) { return value(); }
};


// service_traits::MD5Sum< ::network_tables_node::NTSetRawRequest> should match
// service_traits::MD5Sum< ::network_tables_node::NTSetRaw >
template<>
struct MD5Sum< ::network_tables_node::NTSetRawRequest>
{
  static const char* value()
  {
    return MD5Sum< ::network_tables_node::NTSetRaw >::value();
  }
  static const char* value(const ::network_tables_node::NTSetRawRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::network_tables_node::NTSetRawRequest> should match
// service_traits::DataType< ::network_tables_node::NTSetRaw >
template<>
struct DataType< ::network_tables_node::NTSetRawRequest>
{
  static const char* value()
  {
    return DataType< ::network_tables_node::NTSetRaw >::value();
  }
  static const char* value(const ::network_tables_node::NTSetRawRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::network_tables_node::NTSetRawResponse> should match
// service_traits::MD5Sum< ::network_tables_node::NTSetRaw >
template<>
struct MD5Sum< ::network_tables_node::NTSetRawResponse>
{
  static const char* value()
  {
    return MD5Sum< ::network_tables_node::NTSetRaw >::value();
  }
  static const char* value(const ::network_tables_node::NTSetRawResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::network_tables_node::NTSetRawResponse> should match
// service_traits::DataType< ::network_tables_node::NTSetRaw >
template<>
struct DataType< ::network_tables_node::NTSetRawResponse>
{
  static const char* value()
  {
    return DataType< ::network_tables_node::NTSetRaw >::value();
  }
  static const char* value(const ::network_tables_node::NTSetRawResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NETWORK_TABLES_NODE_MESSAGE_NTSETRAW_H
