// Generated by gencpp from file network_tables_node/NTSetDouble.msg
// DO NOT EDIT!


#ifndef NETWORK_TABLES_NODE_MESSAGE_NTSETDOUBLE_H
#define NETWORK_TABLES_NODE_MESSAGE_NTSETDOUBLE_H

#include <ros/service_traits.h>


#include <network_tables_node/NTSetDoubleRequest.h>
#include <network_tables_node/NTSetDoubleResponse.h>


namespace network_tables_node
{

struct NTSetDouble
{

typedef NTSetDoubleRequest Request;
typedef NTSetDoubleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NTSetDouble
} // namespace network_tables_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::network_tables_node::NTSetDouble > {
  static const char* value()
  {
    return "fb1eb722c775a2e6382a59aeda93db62";
  }

  static const char* value(const ::network_tables_node::NTSetDouble&) { return value(); }
};

template<>
struct DataType< ::network_tables_node::NTSetDouble > {
  static const char* value()
  {
    return "network_tables_node/NTSetDouble";
  }

  static const char* value(const ::network_tables_node::NTSetDouble&) { return value(); }
};


// service_traits::MD5Sum< ::network_tables_node::NTSetDoubleRequest> should match
// service_traits::MD5Sum< ::network_tables_node::NTSetDouble >
template<>
struct MD5Sum< ::network_tables_node::NTSetDoubleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::network_tables_node::NTSetDouble >::value();
  }
  static const char* value(const ::network_tables_node::NTSetDoubleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::network_tables_node::NTSetDoubleRequest> should match
// service_traits::DataType< ::network_tables_node::NTSetDouble >
template<>
struct DataType< ::network_tables_node::NTSetDoubleRequest>
{
  static const char* value()
  {
    return DataType< ::network_tables_node::NTSetDouble >::value();
  }
  static const char* value(const ::network_tables_node::NTSetDoubleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::network_tables_node::NTSetDoubleResponse> should match
// service_traits::MD5Sum< ::network_tables_node::NTSetDouble >
template<>
struct MD5Sum< ::network_tables_node::NTSetDoubleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::network_tables_node::NTSetDouble >::value();
  }
  static const char* value(const ::network_tables_node::NTSetDoubleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::network_tables_node::NTSetDoubleResponse> should match
// service_traits::DataType< ::network_tables_node::NTSetDouble >
template<>
struct DataType< ::network_tables_node::NTSetDoubleResponse>
{
  static const char* value()
  {
    return DataType< ::network_tables_node::NTSetDouble >::value();
  }
  static const char* value(const ::network_tables_node::NTSetDoubleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NETWORK_TABLES_NODE_MESSAGE_NTSETDOUBLE_H
