// Generated by gencpp from file network_tables_node/NTSetBoolArrayRequest.msg
// DO NOT EDIT!


#ifndef NETWORK_TABLES_NODE_MESSAGE_NTSETBOOLARRAYREQUEST_H
#define NETWORK_TABLES_NODE_MESSAGE_NTSETBOOLARRAYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace network_tables_node
{
template <class ContainerAllocator>
struct NTSetBoolArrayRequest_
{
  typedef NTSetBoolArrayRequest_<ContainerAllocator> Type;

  NTSetBoolArrayRequest_()
    : table_name()
    , entry_name()
    , value()  {
    }
  NTSetBoolArrayRequest_(const ContainerAllocator& _alloc)
    : table_name(_alloc)
    , entry_name(_alloc)
    , value(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _table_name_type;
  _table_name_type table_name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _entry_name_type;
  _entry_name_type entry_name;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::network_tables_node::NTSetBoolArrayRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::network_tables_node::NTSetBoolArrayRequest_<ContainerAllocator> const> ConstPtr;

}; // struct NTSetBoolArrayRequest_

typedef ::network_tables_node::NTSetBoolArrayRequest_<std::allocator<void> > NTSetBoolArrayRequest;

typedef boost::shared_ptr< ::network_tables_node::NTSetBoolArrayRequest > NTSetBoolArrayRequestPtr;
typedef boost::shared_ptr< ::network_tables_node::NTSetBoolArrayRequest const> NTSetBoolArrayRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::network_tables_node::NTSetBoolArrayRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::network_tables_node::NTSetBoolArrayRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::network_tables_node::NTSetBoolArrayRequest_<ContainerAllocator1> & lhs, const ::network_tables_node::NTSetBoolArrayRequest_<ContainerAllocator2> & rhs)
{
  return lhs.table_name == rhs.table_name &&
    lhs.entry_name == rhs.entry_name &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::network_tables_node::NTSetBoolArrayRequest_<ContainerAllocator1> & lhs, const ::network_tables_node::NTSetBoolArrayRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace network_tables_node

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::network_tables_node::NTSetBoolArrayRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::network_tables_node::NTSetBoolArrayRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::network_tables_node::NTSetBoolArrayRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::network_tables_node::NTSetBoolArrayRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::network_tables_node::NTSetBoolArrayRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::network_tables_node::NTSetBoolArrayRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::network_tables_node::NTSetBoolArrayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1bf815704bef7a6778ca1537369378bf";
  }

  static const char* value(const ::network_tables_node::NTSetBoolArrayRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1bf815704bef7a67ULL;
  static const uint64_t static_value2 = 0x78ca1537369378bfULL;
};

template<class ContainerAllocator>
struct DataType< ::network_tables_node::NTSetBoolArrayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "network_tables_node/NTSetBoolArrayRequest";
  }

  static const char* value(const ::network_tables_node::NTSetBoolArrayRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::network_tables_node::NTSetBoolArrayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Inputs\n"
"string table_name\n"
"string entry_name\n"
"bool[] value\n"
;
  }

  static const char* value(const ::network_tables_node::NTSetBoolArrayRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::network_tables_node::NTSetBoolArrayRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.table_name);
      stream.next(m.entry_name);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NTSetBoolArrayRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::network_tables_node::NTSetBoolArrayRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::network_tables_node::NTSetBoolArrayRequest_<ContainerAllocator>& v)
  {
    s << indent << "table_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.table_name);
    s << indent << "entry_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.entry_name);
    s << indent << "value[]" << std::endl;
    for (size_t i = 0; i < v.value.size(); ++i)
    {
      s << indent << "  value[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.value[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NETWORK_TABLES_NODE_MESSAGE_NTSETBOOLARRAYREQUEST_H
