// Generated by gencpp from file network_tables_node/NTSetDoubleResponse.msg
// DO NOT EDIT!


#ifndef NETWORK_TABLES_NODE_MESSAGE_NTSETDOUBLERESPONSE_H
#define NETWORK_TABLES_NODE_MESSAGE_NTSETDOUBLERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace network_tables_node
{
template <class ContainerAllocator>
struct NTSetDoubleResponse_
{
  typedef NTSetDoubleResponse_<ContainerAllocator> Type;

  NTSetDoubleResponse_()
    : success(false)
    , last_valid()  {
    }
  NTSetDoubleResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , last_valid()  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef ros::Time _last_valid_type;
  _last_valid_type last_valid;





  typedef boost::shared_ptr< ::network_tables_node::NTSetDoubleResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::network_tables_node::NTSetDoubleResponse_<ContainerAllocator> const> ConstPtr;

}; // struct NTSetDoubleResponse_

typedef ::network_tables_node::NTSetDoubleResponse_<std::allocator<void> > NTSetDoubleResponse;

typedef boost::shared_ptr< ::network_tables_node::NTSetDoubleResponse > NTSetDoubleResponsePtr;
typedef boost::shared_ptr< ::network_tables_node::NTSetDoubleResponse const> NTSetDoubleResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::network_tables_node::NTSetDoubleResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::network_tables_node::NTSetDoubleResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::network_tables_node::NTSetDoubleResponse_<ContainerAllocator1> & lhs, const ::network_tables_node::NTSetDoubleResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.last_valid == rhs.last_valid;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::network_tables_node::NTSetDoubleResponse_<ContainerAllocator1> & lhs, const ::network_tables_node::NTSetDoubleResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace network_tables_node

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::network_tables_node::NTSetDoubleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::network_tables_node::NTSetDoubleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::network_tables_node::NTSetDoubleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::network_tables_node::NTSetDoubleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::network_tables_node::NTSetDoubleResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::network_tables_node::NTSetDoubleResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::network_tables_node::NTSetDoubleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2b9bb09283bd6fd7d537098b659784ab";
  }

  static const char* value(const ::network_tables_node::NTSetDoubleResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2b9bb09283bd6fd7ULL;
  static const uint64_t static_value2 = 0xd537098b659784abULL;
};

template<class ContainerAllocator>
struct DataType< ::network_tables_node::NTSetDoubleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "network_tables_node/NTSetDoubleResponse";
  }

  static const char* value(const ::network_tables_node::NTSetDoubleResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::network_tables_node::NTSetDoubleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Outputs\n"
"bool success\n"
"time last_valid\n"
;
  }

  static const char* value(const ::network_tables_node::NTSetDoubleResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::network_tables_node::NTSetDoubleResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.last_valid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NTSetDoubleResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::network_tables_node::NTSetDoubleResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::network_tables_node::NTSetDoubleResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "last_valid: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.last_valid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NETWORK_TABLES_NODE_MESSAGE_NTSETDOUBLERESPONSE_H
