// Generated by gencpp from file network_tables_node/NTSetDoubleArrayRequest.msg
// DO NOT EDIT!


#ifndef NETWORK_TABLES_NODE_MESSAGE_NTSETDOUBLEARRAYREQUEST_H
#define NETWORK_TABLES_NODE_MESSAGE_NTSETDOUBLEARRAYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace network_tables_node
{
template <class ContainerAllocator>
struct NTSetDoubleArrayRequest_
{
  typedef NTSetDoubleArrayRequest_<ContainerAllocator> Type;

  NTSetDoubleArrayRequest_()
    : table_name()
    , entry_name()
    , value()  {
    }
  NTSetDoubleArrayRequest_(const ContainerAllocator& _alloc)
    : table_name(_alloc)
    , entry_name(_alloc)
    , value(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _table_name_type;
  _table_name_type table_name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _entry_name_type;
  _entry_name_type entry_name;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::network_tables_node::NTSetDoubleArrayRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::network_tables_node::NTSetDoubleArrayRequest_<ContainerAllocator> const> ConstPtr;

}; // struct NTSetDoubleArrayRequest_

typedef ::network_tables_node::NTSetDoubleArrayRequest_<std::allocator<void> > NTSetDoubleArrayRequest;

typedef boost::shared_ptr< ::network_tables_node::NTSetDoubleArrayRequest > NTSetDoubleArrayRequestPtr;
typedef boost::shared_ptr< ::network_tables_node::NTSetDoubleArrayRequest const> NTSetDoubleArrayRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::network_tables_node::NTSetDoubleArrayRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::network_tables_node::NTSetDoubleArrayRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::network_tables_node::NTSetDoubleArrayRequest_<ContainerAllocator1> & lhs, const ::network_tables_node::NTSetDoubleArrayRequest_<ContainerAllocator2> & rhs)
{
  return lhs.table_name == rhs.table_name &&
    lhs.entry_name == rhs.entry_name &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::network_tables_node::NTSetDoubleArrayRequest_<ContainerAllocator1> & lhs, const ::network_tables_node::NTSetDoubleArrayRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace network_tables_node

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::network_tables_node::NTSetDoubleArrayRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::network_tables_node::NTSetDoubleArrayRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::network_tables_node::NTSetDoubleArrayRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::network_tables_node::NTSetDoubleArrayRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::network_tables_node::NTSetDoubleArrayRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::network_tables_node::NTSetDoubleArrayRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::network_tables_node::NTSetDoubleArrayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "00028d6a420ee537029cab624340f25c";
  }

  static const char* value(const ::network_tables_node::NTSetDoubleArrayRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x00028d6a420ee537ULL;
  static const uint64_t static_value2 = 0x029cab624340f25cULL;
};

template<class ContainerAllocator>
struct DataType< ::network_tables_node::NTSetDoubleArrayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "network_tables_node/NTSetDoubleArrayRequest";
  }

  static const char* value(const ::network_tables_node::NTSetDoubleArrayRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::network_tables_node::NTSetDoubleArrayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Inputs\n"
"string table_name\n"
"string entry_name\n"
"float64[] value\n"
;
  }

  static const char* value(const ::network_tables_node::NTSetDoubleArrayRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::network_tables_node::NTSetDoubleArrayRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.table_name);
      stream.next(m.entry_name);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NTSetDoubleArrayRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::network_tables_node::NTSetDoubleArrayRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::network_tables_node::NTSetDoubleArrayRequest_<ContainerAllocator>& v)
  {
    s << indent << "table_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.table_name);
    s << indent << "entry_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.entry_name);
    s << indent << "value[]" << std::endl;
    for (size_t i = 0; i < v.value.size(); ++i)
    {
      s << indent << "  value[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.value[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NETWORK_TABLES_NODE_MESSAGE_NTSETDOUBLEARRAYREQUEST_H
